rozdelenie modulu Formula na Formula, FormulaParser, SignedFormula, Term
FMFI-UK-1-AIN-412/elm-formula pull request #7
Opened 2020-10-12 09:39 UTC by MatejKomlossy

2020-10-15 12:30 UTC, crnkjck requested changes

2020-10-15 12:30 UTC, crnkjck commented on src/Formula.elm
> +    substitute,  freeFormula, removeQuantifierAndSubstitute, isSubformulaOf)
Nitpick: Použite, prosím, rovnakú formátovaciu konvenciu ako v pôvodnom kóde. V Elme (a Haskelli) sa dávajú čiarky na začiatok ďalšieho riadka, nie na koniec predchádzajúceho, zarovnané na zátvorku.

2020-10-15 12:30 UTC, crnkjck commented on src/Formula.elm
>  substF : Substitution -> Set String -> Formula -> Result String Formula
Prípona `F` ako <i>F</i>ormula by mala byť zbytočná. Funkcia by sa mala volať iba `subst`.
Podobne v module `Term` by mala byť funkcia `subst` a `substs`, namiesto `substT` a `substTs`.
Elmovská konvencia je, že namiesto toho, aby bolo meno hlavného dátového typu v menej funkcie, funkcie pri importovaní modulu neexposujete, ale používate ich kvalifikované mená: `Term.subst`, `Term.substs`, …

Podobne aj nižšie – funkcie `functionsTA`, `variablesTA`, … treba prehodiť do modulu `Term` a tu použiť pod kvalifikovanými menami `Term.functionsA`, …

2020-10-15 12:30 UTC, crnkjck commented on src/SignedFormula.elm
> +strSigned : Signed Formula -> String
`toString`

2020-10-15 12:30 UTC, crnkjck commented on src/SignedFormula.elm
> +negSigned : Signed Formula -> Signed Formula
iba `neg`, `Signed` je sucast nazvu typu a modulu. Podobne vo vsetkych dalsich funkciach.

2020-10-15 12:30 UTC, crnkjck commented on src/Formula.elm
`strFormula` by sa mala premenovat na `toString`. Funkcia s rovnakým menom by mala byť v moduloch `Term` a `SignedFormula`.

2020-10-15 12:30 UTC, crnkjck commented on src/Term.elm
> +freeTermA : Term -> Set String -> Set String
Podobne ako inde odstráňte `Term` a `T` z názvov funkcií.

2020-10-15 14:07 UTC, yoyko reviewed
couple more notes

2020-10-15 14:07 UTC, yoyko commented on src/Term.elm
> +substTerm sigma t =
This should be `substitute` (as in `Formula`).
Note @crnkjck 's note about the helpers (substF/T).

2020-10-15 14:07 UTC, yoyko commented on src/Formula.elm
> +    ( Formula(..),  strFormula,
`strFormua` should also be `Formula.toString`

2020-10-15 14:07 UTC, yoyko commented on src/FormulaParser.elm
> +
Maybe move this below, so the `parse`, `parseTerm` and `parseSigned`  methods are first together (or else  `parseTerm` should be next to `term` parser, which would be a bit lost ;).

2020-10-15 14:07 UTC, yoyko commented on src/Term.elm
> +strTerm t =
toString

2020-10-15 14:07 UTC, yoyko commented on src/FormulaParser.elm
> +module FormulaParser exposing (parse, parseSigned, parseTerm)
Make this Formula.Parser (i.e. `src/Formula/Parser.elm`), similar for `Formula.Signed`

2020-10-19 08:56 UTC, crnkjck requested changes
Prosím ešte upraviť pár drobností. Inak je to za mňa super.

2020-10-19 08:56 UTC, crnkjck commented on src/Formula.elm
> +import Term exposing(Term(..), Substitution)
Prosím, použite [`elm-format`](https://github.com/avh4/elm-format) na štandardizáciu formátovania kódu všetkých súborov.

Formátovanie sa dá spustiť kávesovou skratkou alebo automaticky pri uložení súboru, ak používate [VS Code](https://marketplace.visualstudio.com/items?itemName=sbrink.elm#formatting-with-elm-format), [Atom](https://atom.io/packages/elm-format), [Sublime](https://github.com/evancz/elm-format-on-save) a keď pohľadáte, asi aj v ďalších editoroch.

2020-10-19 08:56 UTC, crnkjck commented on src/Formula.elm
Poprosím vás ešte zjednotiť názvy týchto funkcií s `toString`: `binToString`, `qToString`, `Term.argsToString`.

2020-10-19 08:56 UTC, crnkjck commented on src/Term.elm
>  strArgs : List Term -> String
`argsToString`

2020-10-19 20:19 UTC, crnkjck approved these changes

2020-10-19 21:10 UTC, crnkjck commented
@yoyko, za mna mozeme merge

2020-10-21 11:36 UTC, merged